// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Retrieves account information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "updates a account",
                "parameters": [
                    {
                        "description": "input account fields",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                }
            }
        },
        "/activities.ics": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities.ics"
                ],
                "summary": "Get a activities by start and end",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "activities"
                        }
                    }
                }
            }
        },
        "/activity": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Get a activities by start and end",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Activity"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Creates a activity",
                "parameters": [
                    {
                        "description": "input activity",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InputActivity"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Activity"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Stops a activity",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Activity"
                        }
                    }
                }
            }
        },
        "/activity/{desc}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Starts a activity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Activity description",
                        "name": "desc",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Activity"
                        }
                    }
                }
            }
        },
        "/activity/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Get a activity by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Activity id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Activity"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BasicAuth ApiKeyAuth": []
                    },
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Updates a activity",
                "parameters": [
                    {
                        "description": "input activity",
                        "name": "activity",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InputActivity"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Activity id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Activity"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activity"
                ],
                "summary": "Delete a activity",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Activity id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Activity"
                        }
                    }
                }
            }
        },
        "/holiday": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holiday"
                ],
                "summary": "Get a activities by start and end",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Holiday"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holiday"
                ],
                "summary": "Creates a holiday",
                "parameters": [
                    {
                        "description": "Input holiday",
                        "name": "holiday",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InputHoliday"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Holiday"
                        }
                    }
                }
            }
        },
        "/holiday/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holiday"
                ],
                "summary": "Get a holiday by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Holiday id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Holiday"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holiday"
                ],
                "summary": "Updates a holiday",
                "parameters": [
                    {
                        "description": "Input holiday",
                        "name": "holiday",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InputHoliday"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Holiday id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Holiday"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holiday"
                ],
                "summary": "Delete a holiday",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Holiday id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Holiday"
                        }
                    }
                }
            }
        },
        "/holidays.ics": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "holidays.ics"
                ],
                "summary": "Get a holidays by start and end",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "holidays"
                        }
                    }
                }
            }
        },
        "/overview": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "overview"
                ],
                "summary": "Retrieves overview of your overtime",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Calculation date",
                        "name": "date",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Overtime"
                        }
                    }
                }
            }
        },
        "/token": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Retrieves tokens",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Token"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "creates a token",
                "parameters": [
                    {
                        "description": "Input token",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InputToken"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Token"
                        }
                    }
                }
            }
        },
        "/token/{id}": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Delete a token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Token"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "creates a user",
                "parameters": [
                    {
                        "description": "Input user",
                        "name": "bottles",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InputUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/User"
                        }
                    }
                }
            }
        },
        "/webhook": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhook"
                ],
                "summary": "Receives users registered webhooks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Webhook"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "webhook"
                ],
                "summary": "create a webhook",
                "parameters": [
                    {
                        "description": "Webhook",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Webhook"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/Webhook"
                        }
                    }
                }
            }
        },
        "/workday": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workday"
                ],
                "summary": "Retrieves workdays",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date",
                        "name": "end",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/WorkDay"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workday"
                ],
                "summary": "creates a workdays",
                "parameters": [
                    {
                        "description": "Input workday",
                        "name": "workday",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/InputWorkDay"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/WorkDay"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Activity": {
            "type": "object",
            "properties": {
                "ActualDurationInMinutes": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "End": {
                    "type": "string",
                    "format": "date-time",
                    "x-nullable": true
                },
                "EventualDurationInMinutes": {
                    "type": "integer"
                },
                "ID": {
                    "type": "integer"
                },
                "Start": {
                    "type": "string",
                    "format": "date-time",
                    "x-nullable": true
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "Holiday": {
            "type": "object",
            "properties": {
                "Description": {
                    "type": "string"
                },
                "End": {
                    "type": "string",
                    "format": "date-time"
                },
                "ID": {
                    "type": "integer"
                },
                "Start": {
                    "type": "string",
                    "format": "date-time"
                },
                "Type": {
                    "type": "string"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "InputActivity": {
            "type": "object",
            "properties": {
                "Description": {
                    "type": "string"
                },
                "End": {
                    "type": "string",
                    "format": "date-time",
                    "x-nullable": true
                },
                "Start": {
                    "type": "string",
                    "format": "date-time",
                    "x-nullable": true
                }
            }
        },
        "InputHoliday": {
            "type": "object",
            "properties": {
                "Description": {
                    "type": "string"
                },
                "End": {
                    "type": "string",
                    "format": "date-time"
                },
                "Start": {
                    "type": "string",
                    "format": "date-time"
                },
                "Type": {
                    "type": "string"
                }
            }
        },
        "InputToken": {
            "type": "object",
            "properties": {
                "Name": {
                    "type": "string"
                },
                "Readonly": {
                    "type": "boolean"
                }
            }
        },
        "InputUser": {
            "type": "object",
            "properties": {
                "Login": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "NumHolidays": {
                    "type": "integer"
                },
                "NumWorkingDays": {
                    "type": "integer"
                },
                "Password": {
                    "type": "string"
                },
                "Surname": {
                    "type": "string"
                },
                "WeekWorkingTimeInMinutes": {
                    "type": "integer"
                },
                "WorkingDays": {
                    "type": "string"
                }
            }
        },
        "InputWorkDay": {
            "type": "object",
            "properties": {
                "ActiveTime": {
                    "type": "integer"
                },
                "Day": {
                    "type": "string",
                    "format": "date-time"
                },
                "Overtime": {
                    "type": "integer"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "Overtime": {
            "type": "object",
            "properties": {
                "ActiveActivity": {
                    "x-nullable": true,
                    "$ref": "#/definitions/Activity"
                },
                "ActiveTimeThisDayInMinutes": {
                    "type": "integer"
                },
                "ActiveTimeThisMonthInMinutes": {
                    "type": "integer"
                },
                "ActiveTimeThisWeekInMinutes": {
                    "type": "integer"
                },
                "ActiveTimeThisYearInMinutes": {
                    "type": "integer"
                },
                "Date": {
                    "type": "string",
                    "format": "date-time"
                },
                "HolidaysStillAvailable": {
                    "type": "integer"
                },
                "OvertimeThisDayInMinutes": {
                    "type": "integer"
                },
                "OvertimeThisMonthInMinutes": {
                    "type": "integer"
                },
                "OvertimeThisWeekInMinutes": {
                    "type": "integer"
                },
                "OvertimeThisYearInMinutes": {
                    "type": "integer"
                },
                "UsedHolidays": {
                    "type": "integer"
                },
                "WeekNumber": {
                    "type": "integer"
                }
            }
        },
        "Token": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "Name": {
                    "type": "string"
                },
                "Readonly": {
                    "type": "boolean"
                },
                "Token": {
                    "type": "string"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "User": {
            "type": "object",
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "Login": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "NumHolidays": {
                    "type": "integer"
                },
                "NumWorkingDays": {
                    "type": "integer"
                },
                "Surname": {
                    "type": "string"
                },
                "Tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Token"
                    }
                },
                "WeekWorkingTimeInMinutes": {
                    "type": "integer"
                },
                "WorkingDays": {
                    "type": "string"
                }
            }
        },
        "Webhook": {
            "type": "object",
            "properties": {
                "HeaderKey": {
                    "type": "string"
                },
                "HeaderValue": {
                    "type": "string"
                },
                "ID": {
                    "type": "integer"
                },
                "ReadOnly": {
                    "type": "boolean"
                },
                "TargetURL": {
                    "type": "string"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        },
        "WorkDay": {
            "type": "object",
            "properties": {
                "ActiveTime": {
                    "type": "integer"
                },
                "Day": {
                    "type": "string",
                    "format": "date-time"
                },
                "ID": {
                    "type": "integer"
                },
                "IsHoliday": {
                    "type": "boolean"
                },
                "Overtime": {
                    "type": "integer"
                },
                "UserID": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminAuth": {
            "type": "apiKey",
            "name": "adminToken",
            "in": "query"
        },
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Your Overtime API",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
