basePath: /api/v1
definitions:
  pkg.Activity:
    properties:
      CreatedAt:
        type: string
      Description:
        type: string
      End:
        type: string
      ID:
        type: integer
      Start:
        type: string
      UpdatedAt:
        type: string
      UserID:
        type: integer
    type: object
  pkg.Employee:
    properties:
      CreatedAt:
        type: string
      ID:
        type: integer
      Login:
        type: string
      Name:
        type: string
      NumHolidays:
        type: integer
      NumWorkingDays:
        type: integer
      Surname:
        type: string
      Tokens:
        items:
          $ref: '#/definitions/pkg.Token'
        type: array
      UpdatedAt:
        type: string
      WeekWorkingTimeInMinutes:
        type: integer
      WorkingDays:
        type: string
    type: object
  pkg.Holiday:
    properties:
      CreatedAt:
        type: string
      Description:
        type: string
      End:
        type: string
      ID:
        type: integer
      Start:
        type: string
      Type:
        type: string
      UpdatedAt:
        type: string
      UserID:
        type: integer
    type: object
  pkg.InputActivity:
    properties:
      Description:
        type: string
      End:
        type: string
      Start:
        type: string
    type: object
  pkg.InputEmployee:
    properties:
      Login:
        type: string
      Name:
        type: string
      NumHolidays:
        type: integer
      NumWorkingDays:
        type: integer
      Password:
        type: string
      Surname:
        type: string
      WeekWorkingTimeInMinutes:
        type: integer
      WorkingDays:
        type: string
    type: object
  pkg.InputHoliday:
    properties:
      Description:
        type: string
      End:
        type: string
      Start:
        type: string
      Type:
        type: string
    type: object
  pkg.InputToken:
    properties:
      Name:
        type: string
    type: object
  pkg.InputWorkDay:
    properties:
      ActiveTime:
        type: integer
      Day:
        type: string
      Overtime:
        type: integer
      UserID:
        type: integer
    type: object
  pkg.Overview:
    properties:
      ActiveActivity:
        $ref: '#/definitions/pkg.Activity'
      ActiveTimeThisDayInMinutes:
        type: integer
      ActiveTimeThisMonthInMinutes:
        type: integer
      ActiveTimeThisWeekInMinutes:
        type: integer
      ActiveTimeThisYearInMinutes:
        type: integer
      Date:
        type: string
      HolidaysStillAvailable:
        type: integer
      OvertimeThisDayInMinutes:
        type: integer
      OvertimeThisMonthInMinutes:
        type: integer
      OvertimeThisWeekInMinutes:
        type: integer
      OvertimeThisYearInMinutes:
        type: integer
      UsedHolidays:
        type: integer
      WeekNumber:
        type: integer
    type: object
  pkg.Token:
    properties:
      CreatedAt:
        type: string
      ID:
        type: integer
      Name:
        type: string
      Token:
        type: string
      UpdatedAt:
        type: string
      UserID:
        type: integer
    type: object
  pkg.Webhook:
    properties:
      CreatedAt:
        type: string
      HeaderKey:
        type: string
      HeaderValue:
        type: string
      ID:
        type: integer
      ReadOnly:
        type: boolean
      TargetURL:
        type: string
      UpdatedAt:
        type: string
      UserID:
        type: integer
    type: object
  pkg.WorkDay:
    properties:
      ActiveTime:
        type: integer
      CreatedAt:
        type: string
      Day:
        type: string
      ID:
        type: integer
      IsHoliday:
        type: boolean
      Overtime:
        type: integer
      UpdatedAt:
        type: string
      UserID:
        type: integer
    type: object
info:
  contact: {}
  title: Your Overtime API
  version: "1.0"
paths:
  /account:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Employee'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Retrieves account information
      tags:
      - account
    patch:
      parameters:
      - description: input account fields
        in: body
        name: account
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Employee'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: updates a account
      tags:
      - account
  /activity:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Stops a activity
      tags:
      - activity
    get:
      parameters:
      - description: Start date
        in: query
        name: start
        required: true
        type: string
      - description: End date
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.Activity'
            type: array
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Get a activities by start and end
      tags:
      - activity
    post:
      parameters:
      - description: input activity
        in: body
        name: activity
        required: true
        schema:
          $ref: '#/definitions/pkg.InputActivity'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Creates a activity
      tags:
      - activity
  /activity/{desc}:
    post:
      parameters:
      - description: Activity description
        in: path
        name: desc
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Starts a activity
      tags:
      - activity
  /activity/{id}:
    delete:
      parameters:
      - description: Activity id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Delete a activity
      tags:
      - activity
    get:
      parameters:
      - description: Activity id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Get a activity by id
      tags:
      - activity
    put:
      parameters:
      - description: input activity
        in: body
        name: activity
        required: true
        schema:
          $ref: '#/definitions/pkg.InputActivity'
      - description: Activity id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      security:
      - BasicAuth ApiKeyAuth: []
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Updates a activity
      tags:
      - activity
  /employee:
    post:
      parameters:
      - description: Input employee
        in: body
        name: bottles
        required: true
        schema:
          $ref: '#/definitions/pkg.InputEmployee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Employee'
      security:
      - AdminAuth: []
      summary: creates a employee
      tags:
      - employee
  /holiday:
    get:
      parameters:
      - description: Start date
        in: query
        name: start
        required: true
        type: string
      - description: End date
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.Holiday'
            type: array
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Get a activities by start and end
      tags:
      - holiday
    post:
      parameters:
      - description: Input holiday
        in: body
        name: holiday
        required: true
        schema:
          $ref: '#/definitions/pkg.InputHoliday'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Holiday'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Creates a holiday
      tags:
      - holiday
  /holiday/{id}:
    delete:
      parameters:
      - description: Holiday id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Holiday'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Delete a holiday
      tags:
      - holiday
    get:
      parameters:
      - description: Holiday id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Holiday'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Get a holiday by id
      tags:
      - holiday
    put:
      parameters:
      - description: Input holiday
        in: body
        name: holiday
        required: true
        schema:
          $ref: '#/definitions/pkg.InputHoliday'
      - description: Holiday id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Holiday'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Updates a holiday
      tags:
      - holiday
  /overview:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Overview'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Retrieves overview of your overtime
      tags:
      - overview
  /token:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.Token'
            type: array
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Retrieves tokens
      tags:
      - token
    post:
      parameters:
      - description: Input token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/pkg.InputToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Token'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: creates a token
      tags:
      - token
  /token/{id}:
    delete:
      parameters:
      - description: Token id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Token'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Delete a token
      tags:
      - token
  /webhook:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.Webhook'
            type: array
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Receives employees registered webhooks
      tags:
      - webhook
    post:
      parameters:
      - description: Webhook
        in: body
        name: webhook
        required: true
        schema:
          $ref: '#/definitions/pkg.Webhook'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/pkg.Webhook'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: create a webhook
      tags:
      - webhook
  /workday:
    get:
      parameters:
      - description: Start date
        in: query
        name: start
        required: true
        type: string
      - description: End date
        in: query
        name: end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.WorkDay'
            type: array
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: Retrieves workdays
      tags:
      - workday
    post:
      parameters:
      - description: Input workday
        in: body
        name: workday
        required: true
        schema:
          $ref: '#/definitions/pkg.InputWorkDay'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.WorkDay'
      security:
      - BasicAuth: []
      - ApiKeyAuth: []
      summary: creates a workdays
      tags:
      - workday
securityDefinitions:
  AdminAuth:
    in: query
    name: adminToken
    type: apiKey
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
