definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  pkg.Activity:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      end:
        type: string
      id:
        type: integer
      start:
        type: string
      updatedAt:
        type: string
      userID:
        type: integer
    type: object
  pkg.Overview:
    properties:
      activeActivity:
        $ref: '#/definitions/pkg.Activity'
      activeTimeThisDayInMinutes:
        type: integer
      activeTimeThisMonthInMinutes:
        type: integer
      activeTimeThisWeekInMinutes:
        type: integer
      activeTimeThisYearInMinutes:
        type: integer
      date:
        type: string
      holidaysStillAvailable:
        type: integer
      overtimeThisDayInMinutes:
        type: integer
      overtimeThisMonthInMinutes:
        type: integer
      overtimeThisWeekInMinutes:
        type: integer
      overtimeThisYearInMinutes:
        type: integer
      usedHolidays:
        type: integer
      weekNumber:
        type: integer
    type: object
info:
  contact: {}
paths:
  /activity:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      summary: Stops a activity
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      summary: Get a activities by start and end
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      summary: Creates a activity
  /activity/:desc:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      summary: Starts a activity
  /activity/:id:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      summary: Delete a activity
    put:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Activity'
      summary: Updates a activity
  /overview:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Overview'
      summary: Retrieves overview of your overtime
swagger: "2.0"
